### ISSUE TITLE
缺少strings.h

### ISSUE THREAD

**Issue by 4DBA** [xyb930826/CamCADSystem#1]
能不能提供一份release orz

**Comment by cjh0613** [comment]
C 语言 IDE 一般自带此文件，将其引入即可。如果缺失，这里的应该能用：

[include.zip](https://github.com/supercoderhawk/CamCADSystem/files/5847968/include.zip)

**Comment by 4DBA** [comment]
谢谢，vs 2019的文件夹确实没包含string.h，使用该压缩包已解决
